#pragma once

#include <file_config.h>
#include <prj_config.h>

#define EXT_Q(x) #x
#define EXT_QUOTE_VER(mj, mn) EXT_Q(mj.mn)

#if !defined(VER_PRODUCTVERSION) && defined(VER_PRODUCTVERSION_MAJOR)
#	define VER_PRODUCTVERSION	VER_PRODUCTVERSION_MAJOR,VER_PRODUCTVERSION_MINOR,0,0
#endif

#if !defined(VER_PRODUCTVERSION_STR) && defined(VER_PRODUCTVERSION_MAJOR)
#	define VER_PRODUCTVERSION_STR EXT_QUOTE_VER(VER_PRODUCTVERSION_MAJOR, VER_PRODUCTVERSION_MINOR)
#endif
